import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';
import { Menu } from '@/components/Menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: '#4481a2' },
      }}
    >
      <html lang="en">
        <body className={`${inter.className} overflow-hidden h-[100dvh]`}>
          <div className="h-screen flex flex-col">
            <Header />

            <div className="flex gap-4 justify-between grow bg-teal-50">
              <Menu />
              <main className="w-full grid grid-cols-2 gap-4 justify-between grow">
                {children}
              </main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
